### ISSUE TITLE
Remap Fn Key

### ISSUE THREAD

**Issue by kettenfett** [tapiau/fApple-A1243-keyboard-layout#1]
Hi,

I noticed you actually managed to find a way to remap all the keys, including the Fn key on this lovely keyboard.
This is something that remap software like the popular sharpkeys can't do. 

Randyrants, the author of Sharpkeys even adresses this in the [FAQ](https://github.com/randyrants/sharpkeys/):

> Q: Why can't I remap my Fn key on my [notebook or Apple] keyboard?
>A: Some keys simply just never get to Windows. In the case of most Fn keys, they are interpretted by the hardware and never get passed onto the OS, no matter how they appear to work... if Windows doesn't see the key, there's no way for the key to be remapped by Windows.

So I was thinking:

Would it be possible for you to make a small tool, that can permanently remaps the Fn key to something Sharpkeys can recognize - so that, from then on, it'd be possible to remap the key (that formerly has been the Fn key) to something else using Sharpkeys ?

**Comment by tapiau** [comment]
I can't help You - I have not enough knowledge.

I suppose if You are asking about Fn key in laptop - this key probably is handled by keyboard-driver chip, not by software in OS - so to OS is passed scancode from Fn+key combination, not Fn AND key separately. But it is only a suspicion.

In this driver I didn't try to remap Fn key - only swap commands and alts.
